{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-10879",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://patchwork.ozlabs.org/patch/928666/",
          "name": "http://patchwork.ozlabs.org/patch/928666/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "http://patchwork.ozlabs.org/patch/928667/",
          "name": "http://patchwork.ozlabs.org/patch/928667/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "http://www.securityfocus.com/bid/104902",
          "name": "104902",
          "refsource": "BID",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.kernel.org/show_bug.cgi?id=200001",
          "name": "https://bugzilla.kernel.org/show_bug.cgi?id=200001",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10879",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=513f86d73855ce556ea9522b6bfd79f87356dc3a",
          "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=513f86d73855ce556ea9522b6bfd79f87356dc3a",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5369a762c882c0b6e9599e4ebbb3a9ba9eee7e2d",
          "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5369a762c882c0b6e9599e4ebbb3a9ba9eee7e2d",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
          "name": "[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package",
          "refsource": "MLIST",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-1/",
          "name": "USN-3753-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-2/",
          "name": "USN-3753-2",
          "refsource": "UBUNTU",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-07-26T18:29Z",
  "lastModifiedDate": "2018-08-24T10:29Z"
}