{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-10930",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2607",
          "name": "RHSA-2018:2607",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2018:2608",
          "name": "RHSA-2018:2608",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10930",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10930",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://review.gluster.org/#/c/glusterfs/+/21068/",
          "name": "https://review.gluster.org/#/c/glusterfs/+/21068/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in RPC request using gfs3_rename_req in glusterfs server. An authenticated attacker could use this flaw to write to a destination outside the gluster volume."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-09-04T16:29Z",
  "lastModifiedDate": "2018-09-05T10:29Z"
}