{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2016-8647",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://access.redhat.com/errata/RHSA-2017:1685",
          "name": "RHSA-2017:1685",
          "refsource": "REDHAT",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/ansible/ansible-modules-core/pull/5388",
          "name": "https://github.com/ansible/ansible-modules-core/pull/5388",
          "refsource": "CONFIRM",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An input validation vulnerability was found in Ansible's mysql_user module before 2.2.1.0, which may fail to correctly change a password in certain circumstances. Thus the previous password would still be active when it should have been changed."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-07-26T14:29Z",
  "lastModifiedDate": "2018-07-28T01:29Z"
}