{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-10881",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://patchwork.ozlabs.org/patch/929792/",
          "name": "http://patchwork.ozlabs.org/patch/929792/",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "http://www.securityfocus.com/bid/104901",
          "name": "104901",
          "refsource": "BID",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
          "name": "https://bugzilla.kernel.org/show_bug.cgi?id=200015",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10881",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
          "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6e8ab72a812396996035a37e5ca4b3b99b5d214b",
          "refsource": "CONFIRM",
          "tags": [

          ]
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html",
          "name": "[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package",
          "refsource": "MLIST",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3752-1/",
          "name": "USN-3752-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3752-2/",
          "name": "USN-3752-2",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3752-3/",
          "name": "USN-3752-3",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-1/",
          "name": "USN-3753-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3753-2/",
          "name": "USN-3753-2",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3754-1/",
          "name": "USN-3754-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bound access in ext4_get_group_info function, a denial of service, and a system crash by mounting and operating on a crafted ext4 filesystem image."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-07-26T18:29Z",
  "lastModifiedDate": "2018-08-29T10:29Z"
}